/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturatron.Dominio;

/**
 *
 * @author octavioruizcastillo
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 02:42:25 AM CDT 
//


import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

public enum UsoCFDIEnum {

    G01("Adquisición de mercancias"),
    G02("Devoluciones, descuentos o bonificaciones"),
    G03("Gastos en general"),
    I01("Construcciones"),
    I02("Mobilario y equipo de oficina por inversiones"),
    I03("Equipo de transporte"),
    I04("Equipo de computo y accesorios"),
    I05("Dados, troqueles, moldes, matrices y herramental"),
    I06("Comunicaciones telefónicas"),
    I07("Comunicaciones satelitales"),
    I08("Otra maquinaria y equipo"),
    D01("Honorarios médicos, dentales y gastos hospitalarios."),
    D02("Gastos médicos por incapacidad o discapacidad"),
    D03("Gastos funerales."),
    D04("Donativos."),
    D05("Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)."),
    D06("Aportaciones voluntarias al SAR."),
    D07("Primas por seguros de gastos médicos."),
    D08("Gastos de transportación escolar obligatoria."),
    D09("Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones."),
    D10("Pagos por servicios educativos (colegiaturas)"),
    P01("Por definir");
    
    String descripcion;

    UsoCFDIEnum(String descripcion) {
        this.descripcion = descripcion;
    }
   
    public String toString() {
        return descripcion;
    }

}
