/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfiguracionForm.java
 *
 * Created on 27/12/2010, 10:37:27 PM
 */
package com.phesus.facturatron.presentation.mvc.view;

import facturatron.config.ConfiguracionDao;
import facturatron.mvc.Model;
import facturatron.mvc.ViewInterface;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Octavio
 */
public class ConfiguracionForm extends javax.swing.JPanel implements Observer, ViewInterface<ConfiguracionDao> {

    /**
     * Constante para indicar que no se usar autenticación contra el servidor
     * SMTP.
     */
    public static final String SIN_SEGURIDAD = "NO";
    /**
     * Constante para indicar que se va a usar autenticación contra el servidor
     * SMTP y se usa SSL.
     */
    public static final String USA_SSL = "SSL";
    /**
     * Constante para indicar que se va a usar autenticación contra el servidor
     * SMTP y se usa TLS.
     */
    public static final String USA_TLS = "TLS";
    /**
     * Constante para indicar que el visor a usarse es el de Java.
     */
    public static final String VISOR_PDF_JAVA = "VISOR_JAVA";
    /**
     * Constante para indicar que el visor a usarse en el Nativo del SO.
     */
    public static final String VISOR_PDF_NATIVO = "VISOR_NATIVO";
    private ConfiguracionDao model;

    /**
     * Creates new form ConfiguracionForm
     */
    public ConfiguracionForm() {
        initComponents();
    }

    @Override
    public ConfiguracionDao getModel() {
        return model;
    }

    @Override
    public void setModel(ConfiguracionDao model) {
        this.model = model;
    }

    @Override
    public void update(Observable o, Object arg) {
        getTxtPassBd().setText(getModel().getPassBd());
        getTxtPassCer().setText(getModel().getpassCer());
        getTxtPathCer().setText(getModel().getpathCer());
        getTxtPathKey().setText(getModel().getpathKey());
        getTxtPathPdf().setText(getModel().getPathPdf());
        getTxtPathPlantilla().setText(getModel().getPathPlantilla());
        getTxtPathLogo().setText(getModel().getPathLogo());
        getTxtPathXml().setText(getModel().getPathXml());
        getTxtUrlBd().setText(getModel().getUrlBd());
        getTxtUserBd().setText(getModel().getUserBd());
        getTxtSmtpHost().setText(getModel().getSmtpHost());
        getTxtUsuarioSmtp().setText(getModel().getUsuarioSmtp());
        getTxtClaveSmtp().setText(getModel().getClaveSmtp());
        if (getModel().getSeguridad() != null) {
            getRbnSinSeguridad().setSelected(getModel().getSeguridad().equals(SIN_SEGURIDAD));
            getRbnUsaSSL().setSelected(getModel().getSeguridad().equals(USA_SSL));
            getRbnUsaTLS().setSelected(getModel().getSeguridad().equals(USA_TLS));
        } else {
            getRbnSinSeguridad().setSelected(true);
        }
        getTxtPuertoSmtp().setText(getModel().getPuertoSmtp() == null ? "25" : getModel().getPuertoSmtp());
        getTxtCorreoRemitente().setText(getModel().getCorreoRemitente());
        getTxtMensajeCorreo().setText(getModel().getMensajeCorreo());
        getTxtTituloCorreo().setText(getModel().getTituloCorreo());
        if (getModel().getVisorPDF() == null) {
            getRbnVisorPDFNativo().setSelected(true);
        } else {
            getRbnVisorPDFJava().setSelected(getModel().getVisorPDF().equals(VISOR_PDF_JAVA));
            getRbnVisorPDFNativo().setSelected(getModel().getVisorPDF().equals(VISOR_PDF_NATIVO));
        }
        if(getModel().getModuloProductosActivo() != null)
            getBoxProductos().setSelected(getModel().getModuloProductosActivo());
        if(getModel().getModuloUnidadesActivo() != null)
            getBoxUnidades().setSelected(getModel().getModuloUnidadesActivo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupSeguridad = new javax.swing.ButtonGroup();
        btnGroupVisorPDF = new javax.swing.ButtonGroup();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        txtPassCer = new javax.swing.JPasswordField();
        txtPathKey = new org.jdesktop.swingx.JXTextField();
        txtPathCer = new org.jdesktop.swingx.JXTextField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        btnBuscarCer = new org.jdesktop.swingx.JXButton();
        btnBuscarKey = new org.jdesktop.swingx.JXButton();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        btnBuscarPdf = new org.jdesktop.swingx.JXButton();
        btnBuscarPlantilla = new org.jdesktop.swingx.JXButton();
        btnBuscarXml = new org.jdesktop.swingx.JXButton();
        txtPathPdf = new org.jdesktop.swingx.JXTextField();
        txtPathPlantilla = new org.jdesktop.swingx.JXTextField();
        txtPathXml = new org.jdesktop.swingx.JXTextField();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        rbnVisorPDFNativo = new javax.swing.JRadioButton();
        rbnVisorPDFJava = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtUserBd = new org.jdesktop.swingx.JXTextField();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        txtUrlBd = new org.jdesktop.swingx.JXTextField();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtPassBd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtPathLogo = new org.jdesktop.swingx.JXTextField();
        btnBuscarLogo = new org.jdesktop.swingx.JXButton();
        jXTitledPanel2 = new org.jdesktop.swingx.JXTitledPanel();
        btnGuardar = new org.jdesktop.swingx.JXButton();
        pnlConfiguracionCorreo = new org.jdesktop.swingx.JXTitledPanel();
        lblServidorSMTP = new org.jdesktop.swingx.JXLabel();
        txtSmtpHost = new org.jdesktop.swingx.JXTextField();
        txtUsuarioSmtp = new org.jdesktop.swingx.JXTextField();
        lblUsuarioSMTP = new org.jdesktop.swingx.JXLabel();
        lblClaveSMTP = new org.jdesktop.swingx.JXLabel();
        txtClaveSmtp = new javax.swing.JPasswordField();
        txtPuertoSmtp = new org.jdesktop.swingx.JXTextField();
        lblPuertoSMTP = new org.jdesktop.swingx.JXLabel();
        rbnSinSeguridad = new javax.swing.JRadioButton();
        rbnUsaSSL = new javax.swing.JRadioButton();
        rbnUsaTLS = new javax.swing.JRadioButton();
        lblTituloCorreo = new org.jdesktop.swingx.JXLabel();
        lblTituloCorreo1 = new org.jdesktop.swingx.JXLabel();
        scrMensajeCorreo = new javax.swing.JScrollPane();
        txtMensajeCorreo = new javax.swing.JTextArea();
        lblTituloCorreo2 = new org.jdesktop.swingx.JXLabel();
        txtCorreoRemitente = new org.jdesktop.swingx.JXTextField();
        txtTituloCorreo = new org.jdesktop.swingx.JXTextField();
        btnProbarConfiguracion = new org.jdesktop.swingx.JXButton();
        jXTitledPanel3 = new org.jdesktop.swingx.JXTitledPanel();
        boxUnidades = new javax.swing.JCheckBox();
        boxProductos = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        jXTitledPanel1.setTitle("Configuración del Sistema");
        jXTitledPanel1.setTitleFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtPassCer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtPathKey.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtPathCer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel1.setText("Ruta certificado digital:");
        jXLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jXLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel2.setText("Ruta llave pública:");
        jXLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jXLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel3.setText("Clave certificado:");
        jXLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnBuscarCer.setText("...");

        btnBuscarKey.setText("...");

        jXLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel7.setText("Ruta PDF:");
        jXLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jXLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel8.setText("Ruta Plantilla:");
        jXLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jXLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel9.setText("Ruta XML:");
        jXLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnBuscarPdf.setText("...");

        btnBuscarPlantilla.setText("...");

        btnBuscarXml.setText("...");

        txtPathPdf.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtPathPlantilla.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtPathXml.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jXLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel10.setText("Tipo de Visor PDF:");
        jXLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnGroupVisorPDF.add(rbnVisorPDFNativo);
        rbnVisorPDFNativo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbnVisorPDFNativo.setText("Visor PDF Nativo");

        btnGroupVisorPDF.add(rbnVisorPDFJava);
        rbnVisorPDFJava.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbnVisorPDFJava.setText("Visor PDF Java");

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jXLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel5.setText("Usuario Base de Datos:");
        jXLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jXLabel5, gridBagConstraints);

        txtUserBd.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtUserBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserBdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(txtUserBd, gridBagConstraints);

        jXLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel4.setText("URL Base de datos:");
        jXLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jXLabel4, gridBagConstraints);

        txtUrlBd.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txtUrlBd, gridBagConstraints);

        jXLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jXLabel6.setText("Clave Base de Datos:");
        jXLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jXLabel6, gridBagConstraints);

        txtPassBd.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(txtPassBd, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Logotipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        txtPathLogo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(txtPathLogo, gridBagConstraints);

        btnBuscarLogo.setText("...");
        jPanel2.add(btnBuscarLogo, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jXLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                                .addComponent(rbnVisorPDFNativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbnVisorPDFJava)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPathPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPathCer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPathKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscarCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscarKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTitledPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassCer)
                            .addComponent(txtPathPlantilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPathXml, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPathCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPathKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPathPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbnVisorPDFNativo)
                    .addComponent(rbnVisorPDFJava))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPathPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPathXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTitledPanel2.setTitle("Acciones");

        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout jXTitledPanel2Layout = new javax.swing.GroupLayout(jXTitledPanel2.getContentContainer());
        jXTitledPanel2.getContentContainer().setLayout(jXTitledPanel2Layout);
        jXTitledPanel2Layout.setHorizontalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXTitledPanel2Layout.setVerticalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlConfiguracionCorreo.setOpaque(true);
        pnlConfiguracionCorreo.setTitle("Configuración para el Envío del Correo Electrónico");

        lblServidorSMTP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblServidorSMTP.setText("Servidor SMTP:");
        lblServidorSMTP.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblUsuarioSMTP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioSMTP.setText("Usuario Cuenta SMTP:");
        lblUsuarioSMTP.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblClaveSMTP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClaveSMTP.setText("Clave Cuenta SMTP:");
        lblClaveSMTP.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblPuertoSMTP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPuertoSMTP.setText("Puerto SMTP:");
        lblPuertoSMTP.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnGroupSeguridad.add(rbnSinSeguridad);
        rbnSinSeguridad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbnSinSeguridad.setText("No");
        rbnSinSeguridad.setActionCommand("NO");

        btnGroupSeguridad.add(rbnUsaSSL);
        rbnUsaSSL.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbnUsaSSL.setText("SSL");

        btnGroupSeguridad.add(rbnUsaTLS);
        rbnUsaTLS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbnUsaTLS.setText("TLS");

        lblTituloCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTituloCorreo.setText("Título del Correo:");
        lblTituloCorreo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblTituloCorreo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTituloCorreo1.setText("Mensaje del Correo");
        lblTituloCorreo1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        scrMensajeCorreo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtMensajeCorreo.setColumns(20);
        txtMensajeCorreo.setRows(5);
        scrMensajeCorreo.setViewportView(txtMensajeCorreo);

        lblTituloCorreo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTituloCorreo2.setText("Correo del Remitente:");
        lblTituloCorreo2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnProbarConfiguracion.setText("Probar Configuración");
        btnProbarConfiguracion.setToolTipText("Se enviará un Correo a la Dirección que indique en el Correo del Remitente");

        javax.swing.GroupLayout pnlConfiguracionCorreoLayout = new javax.swing.GroupLayout(pnlConfiguracionCorreo.getContentContainer());
        pnlConfiguracionCorreo.getContentContainer().setLayout(pnlConfiguracionCorreoLayout);
        pnlConfiguracionCorreoLayout.setHorizontalGroup(
            pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                        .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsuarioSMTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblClaveSMTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPuertoSMTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfiguracionCorreoLayout.createSequentialGroup()
                        .addComponent(lblServidorSMTP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                        .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSmtpHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsuarioSmtp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTituloCorreo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTituloCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtCorreoRemitente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                        .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                                .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProbarConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                                        .addComponent(txtPuertoSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbnSinSeguridad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbnUsaSSL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbnUsaTLS)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                                .addComponent(txtClaveSmtp)
                                .addGap(32, 32, 32)))
                        .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloCorreo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrMensajeCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))))
                .addGap(9, 9, 9))
        );
        pnlConfiguracionCorreoLayout.setVerticalGroup(
            pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSmtpHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServidorSMTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioSMTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlConfiguracionCorreoLayout.createSequentialGroup()
                        .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClaveSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClaveSMTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlConfiguracionCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuertoSMTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPuertoSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbnSinSeguridad)
                            .addComponent(rbnUsaSSL)
                            .addComponent(rbnUsaTLS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProbarConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfiguracionCorreoLayout.createSequentialGroup()
                        .addComponent(lblTituloCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrMensajeCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jXTitledPanel3.setTitle("Módulos");

        boxUnidades.setText("Unidades");
        boxUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUnidadesActionPerformed(evt);
            }
        });

        boxProductos.setText("Productos");
        boxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProductosActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("Experimentales");

        javax.swing.GroupLayout jXTitledPanel3Layout = new javax.swing.GroupLayout(jXTitledPanel3.getContentContainer());
        jXTitledPanel3.getContentContainer().setLayout(jXTitledPanel3Layout);
        jXTitledPanel3Layout.setHorizontalGroup(
            jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jXTitledPanel3Layout.setVerticalGroup(
            jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxUnidades)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXTitledPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConfiguracionCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXTitledPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConfiguracionCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTitledPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserBdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserBdActionPerformed

    private void boxUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxUnidadesActionPerformed

    private void boxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxProductosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox boxProductos;
    public javax.swing.JCheckBox boxUnidades;
    private org.jdesktop.swingx.JXButton btnBuscarCer;
    private org.jdesktop.swingx.JXButton btnBuscarKey;
    private org.jdesktop.swingx.JXButton btnBuscarLogo;
    private org.jdesktop.swingx.JXButton btnBuscarPdf;
    private org.jdesktop.swingx.JXButton btnBuscarPlantilla;
    private org.jdesktop.swingx.JXButton btnBuscarXml;
    private javax.swing.ButtonGroup btnGroupSeguridad;
    private javax.swing.ButtonGroup btnGroupVisorPDF;
    private org.jdesktop.swingx.JXButton btnGuardar;
    private org.jdesktop.swingx.JXButton btnProbarConfiguracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel2;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel3;
    private org.jdesktop.swingx.JXLabel lblClaveSMTP;
    private org.jdesktop.swingx.JXLabel lblPuertoSMTP;
    private org.jdesktop.swingx.JXLabel lblServidorSMTP;
    private org.jdesktop.swingx.JXLabel lblTituloCorreo;
    private org.jdesktop.swingx.JXLabel lblTituloCorreo1;
    private org.jdesktop.swingx.JXLabel lblTituloCorreo2;
    private org.jdesktop.swingx.JXLabel lblUsuarioSMTP;
    private org.jdesktop.swingx.JXTitledPanel pnlConfiguracionCorreo;
    private javax.swing.JRadioButton rbnSinSeguridad;
    private javax.swing.JRadioButton rbnUsaSSL;
    private javax.swing.JRadioButton rbnUsaTLS;
    private javax.swing.JRadioButton rbnVisorPDFJava;
    private javax.swing.JRadioButton rbnVisorPDFNativo;
    private javax.swing.JScrollPane scrMensajeCorreo;
    private javax.swing.JPasswordField txtClaveSmtp;
    private org.jdesktop.swingx.JXTextField txtCorreoRemitente;
    private javax.swing.JTextArea txtMensajeCorreo;
    private javax.swing.JPasswordField txtPassBd;
    private javax.swing.JPasswordField txtPassCer;
    private org.jdesktop.swingx.JXTextField txtPathCer;
    private org.jdesktop.swingx.JXTextField txtPathKey;
    private org.jdesktop.swingx.JXTextField txtPathLogo;
    private org.jdesktop.swingx.JXTextField txtPathPdf;
    private org.jdesktop.swingx.JXTextField txtPathPlantilla;
    private org.jdesktop.swingx.JXTextField txtPathXml;
    private org.jdesktop.swingx.JXTextField txtPuertoSmtp;
    private org.jdesktop.swingx.JXTextField txtSmtpHost;
    private org.jdesktop.swingx.JXTextField txtTituloCorreo;
    private org.jdesktop.swingx.JXTextField txtUrlBd;
    private org.jdesktop.swingx.JXTextField txtUserBd;
    private org.jdesktop.swingx.JXTextField txtUsuarioSmtp;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnBuscarCer
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarCer() {
        return btnBuscarCer;
    }

    /**
     * @param btnBuscarCer the btnBuscarCer to set
     */
    public void setBtnBuscarCer(org.jdesktop.swingx.JXButton btnBuscarCer) {
        this.btnBuscarCer = btnBuscarCer;
    }

    /**
     * @return the btnBuscarKey
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarKey() {
        return btnBuscarKey;
    }

    /**
     * @param btnBuscarKey the btnBuscarKey to set
     */
    public void setBtnBuscarKey(org.jdesktop.swingx.JXButton btnBuscarKey) {
        this.btnBuscarKey = btnBuscarKey;
    }

    /**
     * @return the btnGuardar
     */
    public org.jdesktop.swingx.JXButton getBtnGuardar() {
        return btnGuardar;
    }

    /**
     * @param btnGuardar the btnGuardar to set
     */
    public void setBtnGuardar(org.jdesktop.swingx.JXButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    /**
     * @return the txtPassBd
     */
    public javax.swing.JPasswordField getTxtPassBd() {
        return txtPassBd;
    }

    /**
     * @param txtPassBd the txtPassBd to set
     */
    public void setTxtPassBd(javax.swing.JPasswordField txtPassBd) {
        this.txtPassBd = txtPassBd;
    }

    /**
     * @return the txtPassCer
     */
    public javax.swing.JPasswordField getTxtPassCer() {
        return txtPassCer;
    }

    /**
     * @param txtPassCer the txtPassCer to set
     */
    public void setTxtPassCer(javax.swing.JPasswordField txtPassCer) {
        this.txtPassCer = txtPassCer;
    }

    /**
     * @return the txtPathCer
     */
    public org.jdesktop.swingx.JXTextField getTxtPathCer() {
        return txtPathCer;
    }

    /**
     * @param txtPathCer the txtPathCer to set
     */
    public void setTxtPathCer(org.jdesktop.swingx.JXTextField txtPathCer) {
        this.txtPathCer = txtPathCer;
    }

    /**
     * @return the txtPathKey
     */
    public org.jdesktop.swingx.JXTextField getTxtPathKey() {
        return txtPathKey;
    }

    /**
     * @param txtPathKey the txtPathKey to set
     */
    public void setTxtPathKey(org.jdesktop.swingx.JXTextField txtPathKey) {
        this.txtPathKey = txtPathKey;
    }

    /**
     * @return the txtUrlBd
     */
    public org.jdesktop.swingx.JXTextField getTxtUrlBd() {
        return txtUrlBd;
    }

    /**
     * @param txtUrlBd the txtUrlBd to set
     */
    public void setTxtUrlBd(org.jdesktop.swingx.JXTextField txtUrlBd) {
        this.txtUrlBd = txtUrlBd;
    }

    /**
     * @return the txtUserBd
     */
    public org.jdesktop.swingx.JXTextField getTxtUserBd() {
        return txtUserBd;
    }

    /**
     * @param txtUserBd the txtUserBd to set
     */
    public void setTxtUserBd(org.jdesktop.swingx.JXTextField txtUserBd) {
        this.txtUserBd = txtUserBd;
    }

    /**
     * @return the btnBuscarPdf
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarPdf() {
        return btnBuscarPdf;
    }

    /**
     * @return the btnBuscarPlantilla
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarPlantilla() {
        return btnBuscarPlantilla;
    }

    /**
     * @return the btnBuscarXml
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarXml() {
        return btnBuscarXml;
    }

    /**
     * @return the txtPathPdf
     */
    public javax.swing.JTextField getTxtPathPdf() {
        return txtPathPdf;
    }

    /**
     * @return the txtPathPlantilla
     */
    public javax.swing.JTextField getTxtPathPlantilla() {
        return txtPathPlantilla;
    }

    /**
     * @return the txtPathXml
     */
    public javax.swing.JTextField getTxtPathXml() {
        return txtPathXml;
    }

    /**
     * @return the txtClaveSmtp
     */
    public javax.swing.JPasswordField getTxtClaveSmtp() {
        return txtClaveSmtp;
    }

    /**
     * @param txtClaveSmtp the txtClaveSmtp to set
     */
    public void setTxtClaveSmtp(javax.swing.JPasswordField txtClaveSmtp) {
        this.txtClaveSmtp = txtClaveSmtp;
    }

    /**
     * @return the txtSmtpHost
     */
    public org.jdesktop.swingx.JXTextField getTxtSmtpHost() {
        return txtSmtpHost;
    }

    /**
     * @param txtSmtpHost the txtSmtpHost to set
     */
    public void setTxtSmtpHost(org.jdesktop.swingx.JXTextField txtSmtpHost) {
        this.txtSmtpHost = txtSmtpHost;
    }

    /**
     * @return the txtUsuarioSmtp
     */
    public org.jdesktop.swingx.JXTextField getTxtUsuarioSmtp() {
        return txtUsuarioSmtp;
    }

    /**
     * @param txtUsuarioSmtp the txtUsuarioSmtp to set
     */
    public void setTxtUsuarioSmtp(org.jdesktop.swingx.JXTextField txtUsuarioSmtp) {
        this.txtUsuarioSmtp = txtUsuarioSmtp;
    }

    /**
     * @return the rbnSinSeguridad
     */
    public javax.swing.JRadioButton getRbnSinSeguridad() {
        return rbnSinSeguridad;
    }

    /**
     * @param rbnSinSeguridad the rbnSinSeguridad to set
     */
    public void setRbnSinSeguridad(javax.swing.JRadioButton rbnSinSeguridad) {
        this.rbnSinSeguridad = rbnSinSeguridad;
    }

    /**
     * @return the rbnUsaSSL
     */
    public javax.swing.JRadioButton getRbnUsaSSL() {
        return rbnUsaSSL;
    }

    /**
     * @param rbnUsaSSL the rbnUsaSSL to set
     */
    public void setRbnUsaSSL(javax.swing.JRadioButton rbnUsaSSL) {
        this.rbnUsaSSL = rbnUsaSSL;
    }

    /**
     * @return the rbnUsaTLS
     */
    public javax.swing.JRadioButton getRbnUsaTLS() {
        return rbnUsaTLS;
    }

    /**
     * @param rbnUsaTLS the rbnUsaTLS to set
     */
    public void setRbnUsaTLS(javax.swing.JRadioButton rbnUsaTLS) {
        this.rbnUsaTLS = rbnUsaTLS;
    }

    /**
     * @return the txtPuertoSmtp
     */
    public org.jdesktop.swingx.JXTextField getTxtPuertoSmtp() {
        return txtPuertoSmtp;
    }

    /**
     * @param txtPuertoSmtp the txtPuertoSmtp to set
     */
    public void setTxtPuertoSmtp(org.jdesktop.swingx.JXTextField txtPuertoSmtp) {
        this.txtPuertoSmtp = txtPuertoSmtp;
    }

    /**
     * @return the rbnVisorPDFJava
     */
    public javax.swing.JRadioButton getRbnVisorPDFJava() {
        return rbnVisorPDFJava;
    }

    /**
     * @param rbnVisorPDFJava the rbnVisorPDFJava to set
     */
    public void setRbnVisorPDFJava(javax.swing.JRadioButton rbnVisorPDFJava) {
        this.rbnVisorPDFJava = rbnVisorPDFJava;
    }

    /**
     * @return the rbnVisorPDFNativo
     */
    public javax.swing.JRadioButton getRbnVisorPDFNativo() {
        return rbnVisorPDFNativo;
    }

    /**
     * @param rbnVisorPDFNativo the rbnVisorPDFNativo to set
     */
    public void setRbnVisorPDFNativo(javax.swing.JRadioButton rbnVisorPDFNativo) {
        this.rbnVisorPDFNativo = rbnVisorPDFNativo;
    }

    /**
     * @return the txtCorreoRemitente
     */
    public org.jdesktop.swingx.JXTextField getTxtCorreoRemitente() {
        return txtCorreoRemitente;
    }

    /**
     * @param txtCorreoRemitente the txtCorreoRemitente to set
     */
    public void setTxtCorreoRemitente(org.jdesktop.swingx.JXTextField txtCorreoRemitente) {
        this.txtCorreoRemitente = txtCorreoRemitente;
    }

    /**
     * @return the txtMensajeCorreo
     */
    public javax.swing.JTextArea getTxtMensajeCorreo() {
        return txtMensajeCorreo;
    }

    /**
     * @param txtMensajeCorreo the txtMensajeCorreo to set
     */
    public void setTxtMensajeCorreo(javax.swing.JTextArea txtMensajeCorreo) {
        this.txtMensajeCorreo = txtMensajeCorreo;
    }

    /**
     * @return the txtTituloCorreo
     */
    public org.jdesktop.swingx.JXTextField getTxtTituloCorreo() {
        return txtTituloCorreo;
    }

    /**
     * @param txtTituloCorreo the txtTituloCorreo to set
     */
    public void setTxtTituloCorreo(org.jdesktop.swingx.JXTextField txtTituloCorreo) {
        this.txtTituloCorreo = txtTituloCorreo;
    }

    /**
     * @return the btnProbarConfiguracion
     */
    public org.jdesktop.swingx.JXButton getBtnProbarConfiguracion() {
        return btnProbarConfiguracion;
    }

    /**
     * @param btnProbarConfiguracion the btnProbarConfiguracion to set
     */
    public void setBtnProbarConfiguracion(org.jdesktop.swingx.JXButton btnProbarConfiguracion) {
        this.btnProbarConfiguracion = btnProbarConfiguracion;
    }

    /**
     * @return the btnBuscarLogo
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarLogo() {
        return btnBuscarLogo;
    }

    /**
     * @return the txtUrlLogo
     */
    public org.jdesktop.swingx.JXTextField getTxtPathLogo() {
        return txtPathLogo;
    }

    /**
     * @return the boxProductos
     */
    public javax.swing.JCheckBox getBoxProductos() {
        return boxProductos;
    }

    /**
     * @return the boxUnidades
     */
    public javax.swing.JCheckBox getBoxUnidades() {
        return boxUnidades;
    }
}
