
package com.facturainteligente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConexionRemota32", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", wsdlLocation = "file:/Users/octavioruizcastillo/Library/Application%20Support/NetBeans/8.2/config/WebServices/ConexionRemota32-asmx-wsdl/catalog/ConexionRemota32.asmx.wsdl")
public class ConexionRemota32
    extends Service
{

    private final static URL CONEXIONREMOTA32_WSDL_LOCATION;
    private final static WebServiceException CONEXIONREMOTA32_EXCEPTION;
    private final static QName CONEXIONREMOTA32_QNAME = new QName("https://www.appfacturainteligente.com/ConexionRemotaCFDI32", "ConexionRemota32");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/octavioruizcastillo/Library/Application%20Support/NetBeans/8.2/config/WebServices/ConexionRemota32-asmx-wsdl/catalog/ConexionRemota32.asmx.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONEXIONREMOTA32_WSDL_LOCATION = url;
        CONEXIONREMOTA32_EXCEPTION = e;
    }

    public ConexionRemota32() {
        super(__getWsdlLocation(), CONEXIONREMOTA32_QNAME);
    }

    public ConexionRemota32(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONEXIONREMOTA32_QNAME, features);
    }

    public ConexionRemota32(URL wsdlLocation) {
        super(wsdlLocation, CONEXIONREMOTA32_QNAME);
    }

    public ConexionRemota32(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONEXIONREMOTA32_QNAME, features);
    }

    public ConexionRemota32(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConexionRemota32(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConexionRemota32Soap
     */
    @WebEndpoint(name = "ConexionRemota32Soap")
    public ConexionRemota32Soap getConexionRemota32Soap() {
        return super.getPort(new QName("https://www.appfacturainteligente.com/ConexionRemotaCFDI32", "ConexionRemota32Soap"), ConexionRemota32Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConexionRemota32Soap
     */
    @WebEndpoint(name = "ConexionRemota32Soap")
    public ConexionRemota32Soap getConexionRemota32Soap(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.appfacturainteligente.com/ConexionRemotaCFDI32", "ConexionRemota32Soap"), ConexionRemota32Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns ConexionRemota32Soap
     */
    @WebEndpoint(name = "ConexionRemota32Soap12")
    public ConexionRemota32Soap getConexionRemota32Soap12() {
        return super.getPort(new QName("https://www.appfacturainteligente.com/ConexionRemotaCFDI32", "ConexionRemota32Soap12"), ConexionRemota32Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConexionRemota32Soap
     */
    @WebEndpoint(name = "ConexionRemota32Soap12")
    public ConexionRemota32Soap getConexionRemota32Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.appfacturainteligente.com/ConexionRemotaCFDI32", "ConexionRemota32Soap12"), ConexionRemota32Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONEXIONREMOTA32_EXCEPTION!= null) {
            throw CONEXIONREMOTA32_EXCEPTION;
        }
        return CONEXIONREMOTA32_WSDL_LOCATION;
    }

}
