
package com.facturainteligente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConexionRemota32Soap", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConexionRemota32Soap {


    /**
     * Conexión Remota para Generación de CFDI v3.2
     * 
     * @param retencionesLocales
     * @param traslados
     * @param trasladosLocales
     * @param etiquetas
     * @param conceptos
     * @param datosUsuario
     * @param informacionAduanera
     * @param datosReceptor
     * @param datosCFDI
     * @param retenciones
     * @return
     *     returns com.facturainteligente.ArrayOfString
     */
    @WebMethod(operationName = "GenerarCFDIv32", action = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32/GenerarCFDIv32")
    @WebResult(name = "GenerarCFDIv32Result", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
    @RequestWrapper(localName = "GenerarCFDIv32", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.GenerarCFDIv32")
    @ResponseWrapper(localName = "GenerarCFDIv32Response", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.GenerarCFDIv32Response")
    public ArrayOfString generarCFDIv32(
        @WebParam(name = "datosUsuario", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString datosUsuario,
        @WebParam(name = "datosReceptor", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString datosReceptor,
        @WebParam(name = "datosCFDI", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString datosCFDI,
        @WebParam(name = "etiquetas", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString etiquetas,
        @WebParam(name = "conceptos", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString conceptos,
        @WebParam(name = "informacionAduanera", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString informacionAduanera,
        @WebParam(name = "retenciones", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString retenciones,
        @WebParam(name = "traslados", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString traslados,
        @WebParam(name = "retencionesLocales", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString retencionesLocales,
        @WebParam(name = "trasladosLocales", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString trasladosLocales);

    /**
     * Conexión Remota para Generación del Código Bidimensional
     * 
     * @param datosUsuario
     * @param uuid
     * @return
     *     returns com.facturainteligente.ArrayOfString
     */
    @WebMethod(operationName = "GenerarCodigoBidimensional", action = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32/GenerarCodigoBidimensional")
    @WebResult(name = "GenerarCodigoBidimensionalResult", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
    @RequestWrapper(localName = "GenerarCodigoBidimensional", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.GenerarCodigoBidimensional")
    @ResponseWrapper(localName = "GenerarCodigoBidimensionalResponse", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.GenerarCodigoBidimensionalResponse")
    public ArrayOfString generarCodigoBidimensional(
        @WebParam(name = "datosUsuario", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString datosUsuario,
        @WebParam(name = "UUID", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        String uuid);

    /**
     * Conexión Remota para Generar Cancelación CFDI
     * 
     * @param datosUsuario
     * @param listaACancelar
     * @return
     *     returns com.facturainteligente.ArrayOfString
     */
    @WebMethod(operationName = "CancelarCFDI", action = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32/CancelarCFDI")
    @WebResult(name = "CancelarCFDIResult", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
    @RequestWrapper(localName = "CancelarCFDI", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.CancelarCFDI")
    @ResponseWrapper(localName = "CancelarCFDIResponse", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.CancelarCFDIResponse")
    public ArrayOfString cancelarCFDI(
        @WebParam(name = "datosUsuario", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString datosUsuario,
        @WebParam(name = "ListaACancelar", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString listaACancelar);

    /**
     * Enviar por Email el CFDI
     * 
     * @param datosUsuario
     * @param uuid
     * @param email
     * @return
     *     returns com.facturainteligente.ArrayOfString
     */
    @WebMethod(operationName = "EnviarCFDI", action = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32/EnviarCFDI")
    @WebResult(name = "EnviarCFDIResult", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
    @RequestWrapper(localName = "EnviarCFDI", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.EnviarCFDI")
    @ResponseWrapper(localName = "EnviarCFDIResponse", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.EnviarCFDIResponse")
    public ArrayOfString enviarCFDI(
        @WebParam(name = "datosUsuario", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString datosUsuario,
        @WebParam(name = "UUID", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        String uuid,
        @WebParam(name = "email", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        String email);

    /**
     * Obtner Comprobante en PDF
     * 
     * @param datosUsuario
     * @param uuid
     * @return
     *     returns com.facturainteligente.ArrayOfString
     */
    @WebMethod(operationName = "ObtenerPDF", action = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32/ObtenerPDF")
    @WebResult(name = "ObtenerPDFResult", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
    @RequestWrapper(localName = "ObtenerPDF", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.ObtenerPDF")
    @ResponseWrapper(localName = "ObtenerPDFResponse", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.ObtenerPDFResponse")
    public ArrayOfString obtenerPDF(
        @WebParam(name = "datosUsuario", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString datosUsuario,
        @WebParam(name = "UUID", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        String uuid);

    /**
     * Obtner el número de créditos de la cuenta
     * 
     * @param datosUsuario
     * @return
     *     returns com.facturainteligente.ArrayOfString
     */
    @WebMethod(operationName = "ObtenerNumeroCreditos", action = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32/ObtenerNumeroCreditos")
    @WebResult(name = "ObtenerNumeroCreditosResult", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
    @RequestWrapper(localName = "ObtenerNumeroCreditos", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.ObtenerNumeroCreditos")
    @ResponseWrapper(localName = "ObtenerNumeroCreditosResponse", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32", className = "com.facturainteligente.ObtenerNumeroCreditosResponse")
    public ArrayOfString obtenerNumeroCreditos(
        @WebParam(name = "datosUsuario", targetNamespace = "https://www.appfacturainteligente.com/ConexionRemotaCFDI32")
        ArrayOfString datosUsuario);

}
