/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfiguracionForm.java
 *
 * Created on 27/12/2010, 10:37:27 PM
 */

package facturatron.config;

import facturatron.MVC.Model;
import facturatron.MVC.ViewInterface;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Octavio
 */
public class ConfiguracionForm extends javax.swing.JPanel implements Observer, ViewInterface<ConfiguracionDao> {

    private ConfiguracionDao model;
    /** Creates new form ConfiguracionForm */
    public ConfiguracionForm() {
        initComponents();
    }

    @Override
    public ConfiguracionDao getModel() {
        return model;
    }

    @Override
    public void setModel(ConfiguracionDao model) {
        this.model = model;
    }

    @Override
    public void update(Observable o, Object arg) {
        getTxtPassBd().setText(getModel().getPassBd());
        getTxtPassCer().setText(getModel().getpassCer());
        getTxtPathCer().setText(getModel().getpathCer());
        getTxtPathKey().setText(getModel().getpathKey());
        getTxtPathPdf().setText(getModel().getPathPdf());
        getTxtPathPlantilla().setText(getModel().getPathPlantilla());
        getTxtPathXml().setText(getModel().getPathXml());
        getTxtUrlBd().setText(getModel().getUrlBd());
        getTxtUserBd().setText(getModel().getUserBd());
        getTxtSmtpHost().setText(getModel().getSmtpHost());
        getTxtUsuarioSmtp().setText(getModel().getUsuarioSmtp());
        getTxtClaveSmtp().setText(getModel().getClaveSmtp());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        txtUserBd = new org.jdesktop.swingx.JXTextField();
        txtPassCer = new javax.swing.JPasswordField();
        txtPassBd = new javax.swing.JPasswordField();
        txtPathKey = new org.jdesktop.swingx.JXTextField();
        txtUrlBd = new org.jdesktop.swingx.JXTextField();
        txtPathCer = new org.jdesktop.swingx.JXTextField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        btnBuscarCer = new org.jdesktop.swingx.JXButton();
        btnBuscarKey = new org.jdesktop.swingx.JXButton();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        btnBuscarPdf = new org.jdesktop.swingx.JXButton();
        btnBuscarPlantilla = new org.jdesktop.swingx.JXButton();
        btnBuscarXml = new org.jdesktop.swingx.JXButton();
        txtPathPdf = new org.jdesktop.swingx.JXTextField();
        txtPathPlantilla = new org.jdesktop.swingx.JXTextField();
        txtPathXml = new org.jdesktop.swingx.JXTextField();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        txtClaveSmtp = new javax.swing.JPasswordField();
        txtUsuarioSmtp = new org.jdesktop.swingx.JXTextField();
        txtSmtpHost = new org.jdesktop.swingx.JXTextField();
        jXTitledPanel2 = new org.jdesktop.swingx.JXTitledPanel();
        btnGuardar = new org.jdesktop.swingx.JXButton();

        jXTitledPanel1.setTitle("Configuración del Sistema");

        jXLabel1.setText("Ruta certificado digital:");

        jXLabel2.setText("Ruta llave pública:");

        jXLabel3.setText("Clave certificado:");

        jXLabel4.setText("URL Base de datos:");

        jXLabel5.setText("Usuario Base de Datos:");

        jXLabel6.setText("Clave Base de Datos:");

        btnBuscarCer.setText("...");

        btnBuscarKey.setText("...");

        jXLabel7.setText("Ruta PDF:");

        jXLabel8.setText("Ruta Plantilla:");

        jXLabel9.setText("Ruta XML:");

        btnBuscarPdf.setText("...");

        btnBuscarPlantilla.setText("...");

        btnBuscarXml.setText("...");

        jXLabel10.setText("Servidor SMTP:");

        jXLabel11.setText("Usuario Cuenta SMTP:");

        jXLabel12.setText("Clave Cuenta SMTP:");

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPathXml, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtPathPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPathPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPathCer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPathKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassBd)
                            .addComponent(txtUserBd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassCer)
                            .addComponent(txtUrlBd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClaveSmtp)
                            .addComponent(txtUsuarioSmtp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSmtpHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPathCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPathKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPathPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPathPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPathXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUrlBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSmtpHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClaveSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTitledPanel2.setTitle("Acciones");

        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout jXTitledPanel2Layout = new javax.swing.GroupLayout(jXTitledPanel2.getContentContainer());
        jXTitledPanel2.getContentContainer().setLayout(jXTitledPanel2Layout);
        jXTitledPanel2Layout.setHorizontalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXTitledPanel2Layout.setVerticalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTitledPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnBuscarCer;
    private org.jdesktop.swingx.JXButton btnBuscarKey;
    private org.jdesktop.swingx.JXButton btnBuscarPdf;
    private org.jdesktop.swingx.JXButton btnBuscarPlantilla;
    private org.jdesktop.swingx.JXButton btnBuscarXml;
    private org.jdesktop.swingx.JXButton btnGuardar;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel2;
    private javax.swing.JPasswordField txtClaveSmtp;
    private javax.swing.JPasswordField txtPassBd;
    private javax.swing.JPasswordField txtPassCer;
    private org.jdesktop.swingx.JXTextField txtPathCer;
    private org.jdesktop.swingx.JXTextField txtPathKey;
    private org.jdesktop.swingx.JXTextField txtPathPdf;
    private org.jdesktop.swingx.JXTextField txtPathPlantilla;
    private org.jdesktop.swingx.JXTextField txtPathXml;
    private org.jdesktop.swingx.JXTextField txtSmtpHost;
    private org.jdesktop.swingx.JXTextField txtUrlBd;
    private org.jdesktop.swingx.JXTextField txtUserBd;
    private org.jdesktop.swingx.JXTextField txtUsuarioSmtp;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnBuscarCer
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarCer() {
        return btnBuscarCer;
    }

    /**
     * @param btnBuscarCer the btnBuscarCer to set
     */
    public void setBtnBuscarCer(org.jdesktop.swingx.JXButton btnBuscarCer) {
        this.btnBuscarCer = btnBuscarCer;
    }

    /**
     * @return the btnBuscarKey
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarKey() {
        return btnBuscarKey;
    }

    /**
     * @param btnBuscarKey the btnBuscarKey to set
     */
    public void setBtnBuscarKey(org.jdesktop.swingx.JXButton btnBuscarKey) {
        this.btnBuscarKey = btnBuscarKey;
    }

    /**
     * @return the btnGuardar
     */
    public org.jdesktop.swingx.JXButton getBtnGuardar() {
        return btnGuardar;
    }

    /**
     * @param btnGuardar the btnGuardar to set
     */
    public void setBtnGuardar(org.jdesktop.swingx.JXButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    /**
     * @return the txtPassBd
     */
    public javax.swing.JPasswordField getTxtPassBd() {
        return txtPassBd;
    }

    /**
     * @param txtPassBd the txtPassBd to set
     */
    public void setTxtPassBd(javax.swing.JPasswordField txtPassBd) {
        this.txtPassBd = txtPassBd;
    }

    /**
     * @return the txtPassCer
     */
    public javax.swing.JPasswordField getTxtPassCer() {
        return txtPassCer;
    }

    /**
     * @param txtPassCer the txtPassCer to set
     */
    public void setTxtPassCer(javax.swing.JPasswordField txtPassCer) {
        this.txtPassCer = txtPassCer;
    }

    /**
     * @return the txtPathCer
     */
    public org.jdesktop.swingx.JXTextField getTxtPathCer() {
        return txtPathCer;
    }

    /**
     * @param txtPathCer the txtPathCer to set
     */
    public void setTxtPathCer(org.jdesktop.swingx.JXTextField txtPathCer) {
        this.txtPathCer = txtPathCer;
    }

    /**
     * @return the txtPathKey
     */
    public org.jdesktop.swingx.JXTextField getTxtPathKey() {
        return txtPathKey;
    }

    /**
     * @param txtPathKey the txtPathKey to set
     */
    public void setTxtPathKey(org.jdesktop.swingx.JXTextField txtPathKey) {
        this.txtPathKey = txtPathKey;
    }

    /**
     * @return the txtUrlBd
     */
    public org.jdesktop.swingx.JXTextField getTxtUrlBd() {
        return txtUrlBd;
    }

    /**
     * @param txtUrlBd the txtUrlBd to set
     */
    public void setTxtUrlBd(org.jdesktop.swingx.JXTextField txtUrlBd) {
        this.txtUrlBd = txtUrlBd;
    }

    /**
     * @return the txtUserBd
     */
    public org.jdesktop.swingx.JXTextField getTxtUserBd() {
        return txtUserBd;
    }

    /**
     * @param txtUserBd the txtUserBd to set
     */
    public void setTxtUserBd(org.jdesktop.swingx.JXTextField txtUserBd) {
        this.txtUserBd = txtUserBd;
    }

    /**
     * @return the btnBuscarPdf
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarPdf() {
        return btnBuscarPdf;
    }

    /**
     * @return the btnBuscarPlantilla
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarPlantilla() {
        return btnBuscarPlantilla;
    }

    /**
     * @return the btnBuscarXml
     */
    public org.jdesktop.swingx.JXButton getBtnBuscarXml() {
        return btnBuscarXml;
    }

    /**
     * @return the txtPathPdf
     */
    public javax.swing.JTextField getTxtPathPdf() {
        return txtPathPdf;
    }

    /**
     * @return the txtPathPlantilla
     */
    public javax.swing.JTextField getTxtPathPlantilla() {
        return txtPathPlantilla;
    }

    /**
     * @return the txtPathXml
     */
    public javax.swing.JTextField getTxtPathXml() {
        return txtPathXml;
    }

    /**
     * @return the txtClaveSmtp
     */
    public javax.swing.JPasswordField getTxtClaveSmtp() {
        return txtClaveSmtp;
    }

    /**
     * @param txtClaveSmtp the txtClaveSmtp to set
     */
    public void setTxtClaveSmtp(javax.swing.JPasswordField txtClaveSmtp) {
        this.txtClaveSmtp = txtClaveSmtp;
    }

    /**
     * @return the txtSmtpHost
     */
    public org.jdesktop.swingx.JXTextField getTxtSmtpHost() {
        return txtSmtpHost;
    }

    /**
     * @param txtSmtpHost the txtSmtpHost to set
     */
    public void setTxtSmtpHost(org.jdesktop.swingx.JXTextField txtSmtpHost) {
        this.txtSmtpHost = txtSmtpHost;
    }

    /**
     * @return the txtUsuarioSmtp
     */
    public org.jdesktop.swingx.JXTextField getTxtUsuarioSmtp() {
        return txtUsuarioSmtp;
    }

    /**
     * @param txtUsuarioSmtp the txtUsuarioSmtp to set
     */
    public void setTxtUsuarioSmtp(org.jdesktop.swingx.JXTextField txtUsuarioSmtp) {
        this.txtUsuarioSmtp = txtUsuarioSmtp;
    }
}
