/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FacturaObservacionesDialog.java
 *
 * Created on 17/01/2011, 08:10:47 PM
 */

package facturatron.facturacion;

import java.awt.Dialog;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Octavio
 */
public class FacturasRelacionadasDialog extends javax.swing.JDialog {

    boolean cancelar = false;
    /** Creates new form FacturasRelacionadasDialog**/
    public FacturasRelacionadasDialog(java.awt.Frame parent, String facturasRelacionadas, String tipoRelacionFacturas) {
        super(parent, true);
        _FacturasRelacionadasDialog(facturasRelacionadas, tipoRelacionFacturas);
    }
    public FacturasRelacionadasDialog(Dialog parent, String facturasRelacionadas, String tipoRelacionFacturas) {
        super(parent, true);
        _FacturasRelacionadasDialog(facturasRelacionadas, tipoRelacionFacturas);
    }
    private void _FacturasRelacionadasDialog(String facturasRelacionadas, String tipoRelacionFacturas) {
        initComponents();
        setLocationRelativeTo(null);
        getTxtFacturasRelacionadas().setText(facturasRelacionadas);
        getComboBoxFacturasRelacionadas().setSelectedIndex((Integer.parseInt(tipoRelacionFacturas)-1));
    }

    public List<String> lanzar() {
        
        setVisible(true);
        List<String> facturasRelacioandasYRelacion=new ArrayList<>();
        if(cancelar) {
            return null;
        } else {
            facturasRelacioandasYRelacion.add(getTxtFacturasRelacionadas().getText());
            facturasRelacioandasYRelacion.add("0"+(this.getComboBoxFacturasRelacionadas().getSelectedIndex()+1));
            
            return facturasRelacioandasYRelacion;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new org.jdesktop.swingx.JXButton();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        btnCancelar = new org.jdesktop.swingx.JXButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new org.jdesktop.swingx.JXTextArea();
        comboBoxFacturasRelacionadas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Observaciones de la factura");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jXLabel1.setText("Ingresa aquí las facturas relacionadas, una por línea");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        comboBoxFacturasRelacionadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Nota de crédito de los documentos relacionados",
            "Nota de débito de los documentos relacionados",
            "Devolución de mercancía sobre facturas o traslados previos",
            "Sustitución de los CFDI previos",
            "Traslados de mercancias facturados previamente",
            "Factura generada por los traslados previos",
            "CFDI por aplicación de anticipo" }));

jLabel1.setText("Tipo de relación:");

jLabel2.setText("Facturas relacionadas:");

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(comboBoxFacturasRelacionadas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 102, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboBoxFacturasRelacionadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addGap(11, 11, 11)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        cancelar = true;
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnAceptar;
    private org.jdesktop.swingx.JXButton btnCancelar;
    private javax.swing.JComboBox<String> comboBoxFacturasRelacionadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnAceptar
     */
    public org.jdesktop.swingx.JXButton getBtnAceptar() {
        return btnAceptar;
    }

    /**
     * @return the btnCancelar
     */
    public org.jdesktop.swingx.JXButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * @return the txtFacturasRelacionadas
     */
    public org.jdesktop.swingx.JXTextArea getTxtFacturasRelacionadas() {
        return txtObservaciones;
    }

    /**
     * @return the comboBoxFacturasRelacionadas
     */
    public javax.swing.JComboBox<String> getComboBoxFacturasRelacionadas() {
        return comboBoxFacturasRelacionadas;
    }

    /**
     * @param comboBoxFacturasRelacionadas the comboBoxFacturasRelacionadas to set
     */
    public void setComboBoxFacturasRelacionadas(javax.swing.JComboBox<String> comboBoxFacturasRelacionadas) {
        this.comboBoxFacturasRelacionadas = comboBoxFacturasRelacionadas;
    }

}
