/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on 3/12/2010, 11:07:07 PM
 */

package facturatron.Principal;

import java.awt.Component;

/**
 *
 * @author mora
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        this.getPanelEdicion().setAutoFocusOnTabHideClose(true);
        this.getPanelEdicion().setAutoRequestFocus(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        linkFacturar = new org.jdesktop.swingx.JXHyperlink();
        linkFacturasEmitidas = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        linkCatalogo = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        linkCfgFiscal = new org.jdesktop.swingx.JXHyperlink();
        linkCfgSystem = new org.jdesktop.swingx.JXHyperlink();
        linkSalir = new org.jdesktop.swingx.JXHyperlink();
        panelEdicion = new com.jidesoft.swing.JideTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facturatron");

        jXTaskPane1.setTitle("Facturas");

        linkFacturar.setText("Facturar");
        linkFacturar.setUnclickedColor(new java.awt.Color(0, 0, 0));
        jXTaskPane1.getContentPane().add(linkFacturar);

        linkFacturasEmitidas.setText("Facturas Emitidas");
        linkFacturasEmitidas.setUnclickedColor(new java.awt.Color(0, 0, 0));
        linkFacturasEmitidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkFacturasEmitidasActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(linkFacturasEmitidas);

        jXTaskPaneContainer1.add(jXTaskPane1);

        jXTaskPane2.setTitle("Clientes");

        linkCatalogo.setText("Catálogo");
        linkCatalogo.setUnclickedColor(new java.awt.Color(0, 0, 0));
        linkCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkCatalogoActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(linkCatalogo);

        jXTaskPaneContainer1.add(jXTaskPane2);

        jXTaskPane3.setTitle("Sistema");

        linkCfgFiscal.setText("Configuración Fiscal");
        linkCfgFiscal.setUnclickedColor(new java.awt.Color(0, 0, 0));
        jXTaskPane3.getContentPane().add(linkCfgFiscal);

        linkCfgSystem.setText("Configuración Sistema");
        linkCfgSystem.setUnclickedColor(new java.awt.Color(0, 0, 0));
        jXTaskPane3.getContentPane().add(linkCfgSystem);

        linkSalir.setText("Salir");
        linkSalir.setUnclickedColor(new java.awt.Color(0, 0, 0));
        linkSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkSalirActionPerformed(evt);
            }
        });
        jXTaskPane3.getContentPane().add(linkSalir);

        jXTaskPaneContainer1.add(jXTaskPane3);

        panelEdicion.setShowCloseButtonOnTab(true);
        panelEdicion.setShowTabButtons(true);
        panelEdicion.setTabEditingAllowed(true);

        menu.setText("Archivo");

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSalir.setText("Salir");
        menu.add(menuSalir);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(panelEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkFacturasEmitidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkFacturasEmitidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkFacturasEmitidasActionPerformed

    private void linkCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkCatalogoActionPerformed

    private void linkSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_linkSalirActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    public void addTab(String nombre, Component comp) {
        this.getPanelEdicion().addTab(nombre, comp);
        this.getPanelEdicion().setSelectedComponent(comp);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private org.jdesktop.swingx.JXHyperlink linkCatalogo;
    private org.jdesktop.swingx.JXHyperlink linkCfgFiscal;
    private org.jdesktop.swingx.JXHyperlink linkCfgSystem;
    private org.jdesktop.swingx.JXHyperlink linkFacturar;
    private org.jdesktop.swingx.JXHyperlink linkFacturasEmitidas;
    private org.jdesktop.swingx.JXHyperlink linkSalir;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuSalir;
    private com.jidesoft.swing.JideTabbedPane panelEdicion;
    // End of variables declaration//GEN-END:variables



    /**
     * @return the jXTaskPane1
     */
    public org.jdesktop.swingx.JXTaskPane getjXTaskPane1() {
        return jXTaskPane1;
    }

    /**
     * @param jXTaskPane1 the jXTaskPane1 to set
     */
    public void setjXTaskPane1(org.jdesktop.swingx.JXTaskPane jXTaskPane1) {
        this.jXTaskPane1 = jXTaskPane1;
    }

    /**
     * @return the jXTaskPane2
     */
    public org.jdesktop.swingx.JXTaskPane getjXTaskPane2() {
        return jXTaskPane2;
    }

    /**
     * @param jXTaskPane2 the jXTaskPane2 to set
     */
    public void setjXTaskPane2(org.jdesktop.swingx.JXTaskPane jXTaskPane2) {
        this.jXTaskPane2 = jXTaskPane2;
    }

    /**
     * @return the jXTaskPane3
     */
    public org.jdesktop.swingx.JXTaskPane getjXTaskPane3() {
        return jXTaskPane3;
    }

    /**
     * @param jXTaskPane3 the jXTaskPane3 to set
     */
    public void setjXTaskPane3(org.jdesktop.swingx.JXTaskPane jXTaskPane3) {
        this.jXTaskPane3 = jXTaskPane3;
    }

    /**
     * @return the jXTaskPaneContainer1
     */
    public org.jdesktop.swingx.JXTaskPaneContainer getjXTaskPaneContainer1() {
        return jXTaskPaneContainer1;
    }

    /**
     * @param jXTaskPaneContainer1 the jXTaskPaneContainer1 to set
     */
    public void setjXTaskPaneContainer1(org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1) {
        this.jXTaskPaneContainer1 = jXTaskPaneContainer1;
    }

   
    /**
     * @return the linkSalir
     */
    public org.jdesktop.swingx.JXHyperlink getLinkSalir() {
        return linkSalir;
    }

    /**
     * @param linkSalir the linkSalir to set
     */
    public void setLinkSalir(org.jdesktop.swingx.JXHyperlink linkSalir) {
        this.linkSalir = linkSalir;
    }

    /**
     * @return the menuSalir
     */
    public javax.swing.JMenuItem getMenuSalir() {
        return menuSalir;
    }


    /**
     * @return the panelEdicion
     */
    public com.jidesoft.swing.JideTabbedPane getPanelEdicion() {
        return panelEdicion;
    }

    /**
     * @param panelEdicion the panelEdicion to set
     */
    public void setPanelEdicion(com.jidesoft.swing.JideTabbedPane panelEdicion) {
        this.panelEdicion = panelEdicion;
    }

    /**
     * @return the menu
     */
    public javax.swing.JMenu getMenu() {
        return menu;
    }

    /**
     * @param menu the menu to set
     */
    public void setMenu(javax.swing.JMenu menu) {
        this.menu = menu;
    }

    /**
     * @param menuSalir the menuSalir to set
     */
    public void setMenuSalir(javax.swing.JMenuItem menuSalir) {
        this.menuSalir = menuSalir;
    }

   
    /**
     * @return the linkCatalogo
     */
    public org.jdesktop.swingx.JXHyperlink getLinkCatalogo() {
        return linkCatalogo;
    }

    /**
     * @param linkCatalogo the linkCatalogo to set
     */
    public void setLinkCatalogo(org.jdesktop.swingx.JXHyperlink linkCatalogo) {
        this.linkCatalogo = linkCatalogo;
    }

    /**
     * @return the linkFacturar
     */
    public org.jdesktop.swingx.JXHyperlink getLinkFacturar() {
        return linkFacturar;
    }

    /**
     * @param linkFacturar the linkFacturar to set
     */
    public void setLinkFacturar(org.jdesktop.swingx.JXHyperlink linkFacturar) {
        this.linkFacturar = linkFacturar;
    }

    /**
     * @return the linkFacturasEmitidas
     */
    public org.jdesktop.swingx.JXHyperlink getLinkFacturasEmitidas() {
        return linkFacturasEmitidas;
    }

    /**
     * @param linkFacturasEmitidas the linkFacturasEmitidas to set
     */
    public void setLinkFacturasEmitidas(org.jdesktop.swingx.JXHyperlink linkFacturasEmitidas) {
        this.linkFacturasEmitidas = linkFacturasEmitidas;
    }


    /**
     * @return the linkCfgFiscal
     */
    public org.jdesktop.swingx.JXHyperlink getLinkCfgFiscal() {
        return linkCfgFiscal;
    }

    /**
     * @return the linkCfgSystem
     */
    public org.jdesktop.swingx.JXHyperlink getLinkCfgSystem() {
        return linkCfgSystem;
    }


}
